SRC_DIR=src
OUT_DIR=out
CLASS_DIR=$(SRC_DIR)/Classes
MAIN=Main.java
ANTLR4=tools/antlr-4.9.1-complete.jar
PACKAGE_NAME=AutoGeneratedCode

all: Classes

#Criação dos arquivos .class
Classes: AutoGeneratedCode
	javac -d $(CLASS_DIR) -cp .:$(ANTLR4) $(SRC_DIR)/$(PACKAGE_NAME)/src/*.java $(SRC_DIR)/$(MAIN)

#Codigo do Scanner+Parser
AutoGeneratedCode:
	java -jar $(ANTLR4) $(SRC_DIR)/Dart.g4 -o $(SRC_DIR)/$(PACKAGE_NAME) -package $(PACKAGE_NAME)

clean:
	rm -rf $(SRC_DIR)/$(PACKAGE_NAME) $(OUT_DIR) $(CLASS_DIR)

#Testes

run:
	java -cp $(CLASS_DIR):$(ANTLR4) Main dart_sample_code/functions.dart

test_all:
	echo "Starting tests:\n"
	for path in dart_sample_code/*; do\
		echo $$path;\
		java -cp $(CLASS_DIR):$(ANTLR4) Main $$path;\
		echo "\n";\
	done