import org.antlr.v4.runtime.CharStreams;
import org.antlr.v4.runtime.CommonTokenStream;
import AutoGeneratedCode.DartLexer;
import AutoGeneratedCode.DartParser;
import org.antlr.v4.runtime.RecognitionException;

public class Main {
    public static void main(String[] args) {
        //TODO: Leitura de arquivo da entrada.

        DartLexer lexer = new DartLexer(CharStreams.fromString("x() => 24;"));
        DartParser parser = new DartParser(new CommonTokenStream(lexer));

        try {
            parser.start();
        } catch (RecognitionException e) {
            e.printStackTrace();
            System.out.println("PARSE FAILED!");
            return;
        }

        System.out.println("PARSE SUCESSFUL!");
    }
}
