import org.antlr.v4.runtime.CharStreams;
import org.antlr.v4.runtime.CommonTokenStream;
import org.antlr.v4.runtime.RecognitionException;
import java.io.IOException;
import java.lang.ArrayIndexOutOfBoundsException;
import java.nio.file.NoSuchFileException;
import AutoGeneratedCode.DartLexer;
import AutoGeneratedCode.DartParser;

public class Main {
    public static void main(String[] args) {

        try {
            var lexer = new DartLexer(CharStreams.fromFileName(args[0]));
            var parser = new DartParser(new CommonTokenStream(lexer));

            parser.start();

        } catch (RecognitionException e){
            System.out.println("Parse failed!");
            return;
        } catch (ArrayIndexOutOfBoundsException e){
            System.out.println("Please inform a filename!");
            return;
        } catch (NoSuchFileException e){
            System.out.println("File not found!");
            return;
        } catch (IOException e){
            e.printStackTrace();
            return;
        }

        System.out.println("Parse sucessful!");
    }
}
